### PR TITLE
It's my nuxt app from JensonCollins

### PR DESCRIPTION
**Pull request by JensonCollins**

### CODE REVIEW

**Comment by jorgevazquez** [comment]
I'd like to chat with you but I don't see anything on PPH.  How do I get in touch with you?

**Comment by jorgevazquez** [comment]
Has no README, does not work out of the box.

**Comment by JensonCollins** [comment]
I have another repository for backend code made with express.js
This nuxt app can't be executed without this backend code.

**Comment by jorgevazquez** [comment]
And does your app and backend meet the guidelines in the README file?

**Comment by JensonCollins** [comment]
Yeah. But I can't show my README.MD file for now.
Because there are some private information there.
So I will make new Readme file for you

**Comment by jorgevazquez** [comment]
Then your submission is irrelevant.

**Pull request closed without merging**
